config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
  skip: [
    :session,
    :password,
    :registration,
    :confirmation
  ],
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope '(:locale)', locale: /en/ do

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth
    devise_for :users,
    skip: :omniauth_callbacks,
    controllers: {
      sessions:            'users/sessions',
      registrations:       'users/registrations',
      passwords:           'users/passwords',
      confirmations:       'users/confirmations'
    }

    resources :profiles, only: [:show] do
      resources :profile_images, only: [:show]
    end

    resource :profile, except: [:index, :show] do
      collection do
        get 'return_listing' => 'profiles#return_listing'
      end
      resource :profile_image, except: [:index, :show] do
        collection do
          get 'return_listing' => 'profile_images#return_listing'
        end
      end
      resource :identification, except: [:edit, :update]
      resource :bank_account, except: [:edit, :update]
    end

  #  resources :auths

    get 'dashboard'                           => 'dashboard#index'
    get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
    get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
    # get 'reviews'                             => 'profiles#review', as: 'user_review'
    # get 'introductions'                       => 'profiles#introduction', as: 'introduction'

    resources :message_threads, except: [:edit]

    resources :messages do
      collection do
        post 'send_message'
      end
    end

    resources :favorites, only: [:index, :destroy] do
      collection do
        post   '/:listing_id', action: 'create', as: "add"
      end
    end

    resources :listings do
      collection do
        get 'search',        action: 'search'
        get 'search_result', action: 'search_result'
        get 'page/:page',    action: 'index'
      end
      resources :listing_images, only: [:show, :create, :update, :destroy] do
        get 'manage', on: :collection
      end
      #resources :listing_videos do
      #  get 'manage', on: :collection
      #end
      resources :listing_ngevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      resources :listing_okevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      get 'publish',   action: 'publish',   as: 'publish'
      get 'unpublish', action: 'unpublish', as: 'unpublish'
    end

    resources :reservations, only: [:show, :create, :update] do
      resource :reviews do
        resource :review_replies
      end
    end

    #resources :wishlists

    resources :inquiries, only: [:new, :create] do
      collection do
        post :confirm
      end
    end

    if Rails.env.review_app?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    root 'welcome#index'

    get 'templates' => 'templates#invoice'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :check_identification!, except: [:index]
  before_action :set_message_new_instance

  def index
    @unread_messages = MessageThread.unread_messages(current_user.id)
    @never_replied_reservations = Reservation.new_requests(current_user.id).order_by_created_at_desc
    pp @never_replied_reservations
  end

  def host_reservation_manager
    @reservations = Reservation.as_host(current_user).order_by_created_at_desc
  end

  def guest_reservation_manager
    @reservations = Reservation.as_guest(current_user).order_by_created_at_desc
  end

  private

  def set_message_new_instance
    @message = Message.new
  end
end

app/views/dashboard/_progress.html.slim
- if r.requested?
  span.label.status-request.text-pink
    = r.string_of_progress
- elsif r.canceled? || r.listing_closed?
  span.label.status-contact
    = r.string_of_progress
- elsif r.holded?
  span.label.status-withhold.text-blue
    = r.string_of_progress
- elsif r.accepted?
  span.label.status-ok.text-green
    = r.string_of_progress
- elsif r.rejected?
  span.label.status-reject
    = r.string_of_progress

app/views/dashboard/_reservation_item_as_guest.html.slim
- @reservations.each do |r|
  - listing = reservation_to_listing(r)
  - host = reservation_to_host(r)
  li.card-body
    .row.row-table
      .col-md-3
        - if r.requested?
          span.label.text-blue = t '.progress.requested'
        - elsif r.canceled?
          span.label.text-light-gray = t '.progress.canceled'
        - elsif r.accepted?
          span.label.text-green = t '.progress.accepted'
        - elsif r.rejected?
          span.label = t '.progress.rejected'
        - elsif r.holded?
          span.label.text-starlight = t '.progress.holded'
        - else
          span.label.text-danger = t '.progress.unpublished'
      .col-md-5
        = link_to listing.title, listing_path(r.listing_id)
        br
        = listing.location
      .col-md-2
        = link_to user_id_to_name(host.id), profile_path(host.profile.id)
      .col-md-2
        = "#{r.checkin.strftime("%y/%m/%d")}〜#{r.checkout.strftime("%y/%m/%d")}"
      .link-group
        = link_to "#", id: "reservation-item-as-guest-launch-message-#{r.id}", data: { num: r.id } do
          i.fa.fa-envelope-o
          = t('.msg', model: Message.model_name.human)
        = link_to "#", id: "reservation-item-show-receipt-#{r.id}", data: { num: r.id } do
          i.fa.fa-jpy
          = t '.receipt'
    = render partial: 'shared/modals/message_to_host_from_reservation_manger', locals: { r: r, listing: reservation_to_listing(r) }

app/views/dashboard/_reservation_item_as_host.html.slim
- @reservations.each do |r|
  - listing = reservation_to_listing(r)
  - guest = reservation_to_guest(r)
  li.card-body
    .row.row-table
      .col-md-3
        - if r.requested?
          span.label.text-blue = t '.progress.requested'
        - elsif r.canceled?
          span.label.text-light-gray = t '.progress.canceled'
        - elsif r.accepted?
          span.label.text-green = t '.progress.accepted'
        - elsif r.rejected?
          span.label = t '.progress.rejected'
        - elsif r.holded?
          span.label.text-starlight = t '.progress.holded'
        - else
          span.label.text-danger = t '.progress.unpublished'
      .col-md-3
        = link_to listing.title, listing_path(r.listing_id)
      .col-md-2
        = link_to user_id_to_name(r.guest_id), profile_path(r.guest_id)
      .col-md-2
        = "#{r.checkin.strftime("%y/%m/%d")}〜#{r.checkout.strftime("%y/%m/%d")}"
      .col-md-2
        = r.num_of_people
        = t 'unit.people'
      .link-group.reservation-item-as-host-launch-message
        = link_to "#", id: "reservation-item-as-host-launch-message-#{r.id}", data: { num: r.id } do
          - if r.continued?
            i.fa.fa-reply
            = t '.reply'
          - else
            i.fa.fa-envelope-o
            = t('.contact', model: Message.model_name.human)
    = render partial: 'shared/modals/message_to_guest_from_reservation_manger', locals: { r: r, listing: reservation_to_listing(r) }

app/views/dashboard/guest_reservation_manager.html.slim
- provide :title, t('.title', listing: Listing.model_name.human)
= render 'shared/subnav'
.page-container.row-space-top-4.row-space-4
  .row
    .col-md-3
      = render partial: "shared/guest_sidenav"

    - if @reservations.size.zero?
      .col-md-9
        .card
          .card-header
            = t('.title', listing: Listing.model_name.human)
          .card-body
            p.text-lead.row-space-4
              = t '.no_schedule'
            form.hero-searchForm[action="/listings/search", method="get"]
              input[type="hidden" name="search[where]" value="top"]
              input[type="hidden" name="search[num_of_guest]" value="1"]
              .search-form-wrapper
                .location-wrapper
                  input#location2.location-width.location[type="text" autocomplete="off" name="search[location]" placeholder=t('.form.placeholder')]
              = button_tag("", type: "submit", class: "btn btn-primary btn-large", id: "submit_location") do
                = t '.form.submit'
    - else
      .col-lg-9
        .card
          .card-header
            = t('.title', listing: Listing.model_name.human)
          .responsive-table-container
            ul.list-unstyled.list-layout
              li.card-body.hide--sp
                .row.row-table.row-table-header
                  .col-xs-4.col-md-3 = Reservation.human_attribute_name :progress
                  .col-xs-8.col-md-5 = Listing.human_attribute_name :title
                  .col-xs-12.col-md-2 = t 'name.host'
                  .col-xs-12.col-md-2 = Reservation.human_attribute_name :schedule
                  = render partial: 'reservation_item_as_guest', locals: { reservations: @reservations }

app/views/dashboard/host_reservation_manager.html.slim
- rsrv = Reservation.model_name.human
- provide :title, t('.title', rsrv: rsrv)
= render 'shared/subnav'
.page-container.row-space-top-4.row-space-4
  .row
    .col-md-3
      = render partial: "shared/host_sidenav"

    - if @reservations.blank?
      .col-md-9
        .card
          .card-header
            = t('.title', rsrv: rsrv)
          .card-body
            p.text-lead.row-space-4
              = t('.no_req', rsrv_req: rsrv)
    - else
      .col-md-9
        .card
          .card-header
            = t('.title', rsrv: rsrv)
          .responsive-table-container
            ul.list-unstyled.list-layout
              li.card-body.hide--sp
                .row.row-table.row-table-header
                  .col-xs-4.col-md-3 = Reservation.human_attribute_name :progress
                  .col-xs-8.col-md-3 = Listing.human_attribute_name :title
                  .col-xs-12.col-md-2 = t 'name.guest'
                  .col-xs-12.col-md-2 = Reservation.human_attribute_name :schedule
                  .col-xs-12.col-md-2 = Reservation.human_attribute_name :num_of_people
                  = render partial: 'reservation_item_as_host', locals: { reservations: @reservations }

app/views/dashboard/index.html.slim
- provide :title, t('.title')
= render partial: 'shared/subnav'
- model = Message.model_name.human
- profile = Profile.model_name.human
.page-container.row-space-top-4.row-space-8
  .row
    .col-lg-3.hide--md.hide--sp
      .card.row-space-4
        .media.media-photo-block.dashboard-profile-photo.panel-image
          = link_to profile_path(current_user.profile.id)
            = image_tag(profile_image, class: 'img-responsive')
        .card-body
          h2.h3.text-center.row-space-1
            = user_id_to_name(current_user.id)
          ul.list-unstyled.text-center
            li
              = link_to t('.profile.show', profile: profile), profile_path(current_user.profile.id)
            li
              = link_to t('.profile.edit', profile: profile), edit_profile_path

    .col-lg-9.col-md-12
      #alert-panel.card.row-space-4
        .card-header
          = t '.alert.header'
        .card-body
          ul.list-unstyled.list-smooth
            - unless @never_replied_reservations.count.zero?
              li
                = link_to dashboard_host_reservation_manager_path do
                  = t('.alert.host_reservation_manager_link', rsrv_req: t('name.reservation_request'), num: @never_replied_reservations.count)
                  i.fa.fa-chevron-right
            - unless @unread_messages.count.zero?
              li
                = link_to message_threads_path do
                  = t('.alert.message_thread_link', model: model, num: @unread_messages.count)
                  i.fa.fa-chevron-right
            - if @never_replied_reservations.count.zero? && @unread_messages.count.zero?
              .text-center
                p.h5.row-space-2.row-space-top-2
                  = t '.alert.all_read'
      #message-panel.card.row-space-4
        .card-header
          = t('.message.unread_html', model: model, num: @unread_messages.count)
        - if @unread_messages.count.zero?
          .card-body
            .text-center
              p.h5.row-space-top-2.row-space-2
                = t('.message.all_read_html', model: model)
        - else
          ul.list-layout
            - @unread_messages.each do |um|
              - from_user = user_id_to_user_obj(um.from_user_id)
              - from_user_profile = from_user.profile
              li.card-body.thread
                .row
                  .col-md-4
                    .row.row-table
                      .col-xs-3.col-md-5
                        = link_to message_thread_path(um.message_thread_id) do
                          = image_tag(user_id_to_profile_image(um.from_user_id), class: 'img-round size50')
                      .col-xs-9.col-md-7
                        = user_obj_to_name(from_user)
                        .small2
                          = um.created_at.strftime("%m/%d %H:%M")
                  = link_to message_thread_path(um.message_thread_id), class: "link-reset" do
                    .col-md-5
                      .text-muted
                        = um.content
                      .text-muted
                        = from_user_profile.location
                  - if um.reservation_id.present? && !um.reservation_id.zero?
                    - r = reservation_id_to_reservation_obj(um.reservation_id)
                    - l = listing_id_to_listing_obj(um.listing_id)
                    .col-md-3
                      = render partial: 'progress', locals: { r: r }
                      .small1
                        b
                          = t 'unit.price'
                          = l.price
                        span.col-space-left-1
                          = r.num_of_people
                          = t 'unit.people'
                        br
                        = r.schedule.strftime("%m/%d")
                  - else
                    .col-mod-2
                      span.label.status-contact.text-starlight
                        = Settings.message.unread.string
        .card-body
          = link_to t('.message.all', model: model), message_threads_path