config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users,
  skip: [
    :session,
    :password,
    :registration,
    :confirmation
  ],
  controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  scope '(:locale)', locale: /en/ do

    # We define here a route inside the locale thats just saves the current locale in the session
    get 'omniauth/:provider' => 'users/omniauth#localized', as: :localized_omniauth
    devise_for :users,
    skip: :omniauth_callbacks,
    controllers: {
      sessions:            'users/sessions',
      registrations:       'users/registrations',
      passwords:           'users/passwords',
      confirmations:       'users/confirmations'
    }

    resources :profiles, only: [:show] do
      resources :profile_images, only: [:show]
    end

    resource :profile, except: [:index, :show] do
      collection do
        get 'return_listing' => 'profiles#return_listing'
      end
      resource :profile_image, except: [:index, :show] do
        collection do
          get 'return_listing' => 'profile_images#return_listing'
        end
      end
      resource :identification, except: [:edit, :update]
      resource :bank_account, except: [:edit, :update]
    end

  #  resources :auths

    get 'dashboard'                           => 'dashboard#index'
    get 'dashboard/host_reservation_manager'  => 'dashboard#host_reservation_manager'
    get 'dashboard/guest_reservation_manager' => 'dashboard#guest_reservation_manager'
    # get 'reviews'                             => 'profiles#review', as: 'user_review'
    # get 'introductions'                       => 'profiles#introduction', as: 'introduction'

    resources :message_threads, except: [:edit]

    resources :messages do
      collection do
        post 'send_message'
      end
    end

    resources :favorites, only: [:index, :destroy] do
      collection do
        post   '/:listing_id', action: 'create', as: "add"
      end
    end

    resources :listings do
      collection do
        get 'search',        action: 'search'
        get 'search_result', action: 'search_result'
        get 'page/:page',    action: 'index'
      end
      resources :listing_images, only: [:show, :create, :update, :destroy] do
        get 'manage', on: :collection
      end
      #resources :listing_videos do
      #  get 'manage', on: :collection
      #end
      resources :listing_ngevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      resources :listing_okevents do
        get 'manage', on: :collection
        get 'search', on: :collection
        post 'delete_all_day', on: :collection
      end
      get 'publish',   action: 'publish',   as: 'publish'
      get 'unpublish', action: 'unpublish', as: 'unpublish'
    end

    resources :reservations, only: [:show, :create, :update] do
      resource :reviews do
        resource :review_replies
      end
    end

    #resources :wishlists

    resources :inquiries, only: [:new, :create] do
      collection do
        post :confirm
      end
    end

    if Rails.env.review_app?
      mount LetterOpenerWeb::Engine, at: '/letter_opener'
    end

    root 'welcome#index'

    get 'templates' => 'templates#invoice'
  end

end

app/views/shared/_facebook_connect_bar.html.slim
- # shared#facebook_connect_bar
.page-container.facebook-connect-bar.row-space-top-4
  .card
    .card-body
      .row.row-table.prompt-area
        .col-xs-12
          .pull-right.pull-reset.text-center
            = button_tag type: "button", class: "btn btn-fb" do
              i.fa.fa-facebook
              = t '.connect'
            = link_to t('.read_next'), "#", class: "btn hide--sp" 
          .media-body
            h5
              = t('.msg')
      .row.loading-area.hide
        h4.text-center
          = t '.logging_in'

app/views/shared/_footer.html.slim
footer
  .footer-content-container
    .row
      .col-sm-3.hide--sp
        form name="lang_selector"
          select name="langs"
            - I18n.available_locales.each do |l|
              option [value="#{i18n_url_for(params.merge(locale: l))}" selected=(l if l == I18n.locale)] = Settings.langs[l].to_s
      .col-sm-3.hide--sp
        h5
          = t '.corporate.title'
        ul.list-unstyled
          li
            = link_to t('.corporate.about'), '#'
          li
            = link_to t('.corporate.inquiry'), new_inquiry_url
          li
            = link_to t('.corporate.privacy'), '#'
      .col-sm-4.col-sm-offset-4.show--sp
        form name="lang_selector"
          select name="langs2"
            - I18n.available_locales.each do |l|
              option [value="#{i18n_url_for(params.merge(locale: l))}" selected=(l if l == I18n.locale)] = Settings.langs[l].to_s
      .cml-sm-12.row-space-4.show--sp
        ul.list-layout.list-inline.text-center.h5.footer-links--sp
          li
            = link_to t('.corporate.about'), "#", class: "link-contrast"
          li
            = link_to t('.corporate.inquiry'), new_inquiry_url
          li
            = link_to t('.corporate.privacy'), "#", class: "link-contrast"
    hr.hide--sp
    .sns-container.text-center
      h5.hide--sp
        = t '.social_media.title'
      ul.list-unstyled.list-inline
        li
          = link_to '#' do
            i.fa.fa-facebook
        li
          = link_to '#' do
            i.fa.fa-google-plus
        li
          = link_to '#' do
            i.fa.fa-twitter
        li
          = link_to '#' do
            i.fa.fa-instagram
        li
          = link_to '#' do
            i.fa.fa-pinterest
    #copyright.row-space-top-2.text-center
      = t '.copyright'

app/views/shared/_guest_sidenav.html.slim
ul.sidenav-list
  li
    = link_to t('.guest_reservation_manager'), dashboard_guest_reservation_manager_path, aria: {selected: (action_name == "guest_reservation_manager")}, class: "sidenav-item"
  /li
    = link_to t('.joined_listings'), dashboard_guest_reservation_manager_path, aria: {selected: (action_name != "guest_reservation_manager")}, class: "sidenav-item"

app/views/shared/_header.html.slim
#header.common-header
  .header--sp
    = link_to "#", class: "burger--sp" do
      i.fa.fa-reorder
    - unless controller_name == "welcome"
      .title--sp.text-center
        = link_to "javascript:void(0)", class: "header-search-dummy" do
          i.fa.fa-search
          = t '.search'
    - else
      .title--sp.text-center
        = link_to "", root_path, class: "header-logo"
    .action--sp
    nav.nav--sp
      .nav-mask--sp
      - if user_signed_in?
        .nav-content--sp.card.text-contrast.logged-in
          .nav-header
            .nav-profile.clearfix
              .user-item.pull-left
                = link_to edit_profile_path, class: "link-reset user-profile-link" do
                  .media-photo.media-round.user-profile-image
                    = image_tag profile_image, class: 'size28'
                  = current_user.email
            hr
          = render partial: "/shared/sidebar_nav_sp"
      - else
        .nav-content--sp.card.text-contrast
          = render partial: "/shared/sidebar_nav_sp"
    .search-modal-container
      #search-modal--sp.modal[role="dialog" aria-hidden="true"]
        .modal-table
          .modal-cell
            .modal-content
              .card-header.modal-header
                = link_to "", "#", class: "modal-close", data: { dismiss: "modal" }
                .h4 = t '.search'
              .card-body
                .modal-search-wrapper--sp
                  = render partial: '/shared/header_form_sp'
  .header.clearfix.hide--sp
    = link_to "", root_path, class: "header-logo pull-left"
    - unless controller_name == "welcome"
      = render partial: '/shared/header_form'
    ul.nav.pull-right
      li.help-menu.pull-left.hide
        = link_to "#", class: "" do
          = t '.help'
      li.list-your-thing.pull-left
        = link_to t('.new_listing'), new_listing_path, class: "btn btn-host"
    - if user_signed_in?
      ul.nav.pull-right
        li.user-item.pull-left
          = link_to profile_path(current_user.id), class: "", data: { toggle: "dropdown" } do
            .media-photo.media-round.user-profile-image
              = image_tag(profile_image, class: 'size28')
            span.name
              = current_user.email
            i.fa.fa-caret-down
          ul.dropdown-menu.dropdown-menu-top-right[aria-hidden="true"]
            li
              = link_to t('.dashboard'), dashboard_path, rel: "nofollow"
            li
              = link_to t('.listings'), listings_path, rel: "nofollow"
            li
              = link_to t('.host_reservation_manager'), dashboard_host_reservation_manager_path, rel: "nofollow"
            li
              = link_to t('.guest_reservation_manager'), dashboard_guest_reservation_manager_path, rel: "nofollow"
            /li
              /= link_to t('.wishlists'), wishlists_path, rel: "nofollow"
            li
              = link_to t('.profile'), edit_profile_path, rel: "nofollow"
            li
              = link_to t('.account'), edit_user_registration_path, rel: "nofollow"
            li
              = link_to t('.logout'), destroy_user_session_path, method: :delete, rel: "nofollow"
        li.pull-left
          = link_to message_threads_path, rel: "nofollow", class: "alert-sign" do
            i.fa.fa-envelope-o
              span.hidden
                = t('.messages')
            - unless unread_messages == 0
              i.alert-count
                = unread_messages
    - else
      ul.nav.pull-right
        li#sign_up.pull-left
          = link_to new_user_registration_path, rel: "nofollow" do
            = t '.signup'
        li#login.pull-left
          = link_to new_user_session_path, rel: "nofollow" do
            = t '.login'

app/views/shared/_header_form.html.slim
= simple_form_for(:search, url: '/listings/search', html: { method: 'get', class: 'header-searchForm'}) do |f|
  = f.hidden_field :where, value: 'header'
  = f.hidden_field :num_of_guest, value: 1
  i.fa.fa-search
  = f.input_field :location, autocomplete: 'off', placeholder: t('.location.placeholder'), id: 'location', class: 'location'

app/views/shared/_header_form_sp.html.slim
= simple_form_for(:search, url: '/listings/search', html: { method: 'get', class: 'search_form', id: 'search-form-sp' }) do |f|
  = f.hidden_field :where, value: 'top'
  .row
    .col-sm-12
      label[for="header-location--sp"]
        = f.input_field :location, placeholder: t('.location.placeholder'), autocomplete: "off", class: 'input-large location', id: 'header-location--sp'
  .row.row-condensed.row-space-2
    .col-sm-6
      label.checkin
        = f.input_field :schedule, placeholder: t('.schedule.placeholder'), class: 'checkin input-large common-datepicker'
    .col-sm-6
      label.count
        .select.select-block.select-large
          - arr = (1..15).map{|p| ["#{t('.num_of_guest.unit_text', num: p, unit: t('unit.people'))}",p] }
          - arr <<  ["#{t('.num_of_guest.more_than', num: 16, unit: t('unit.people'))}", :"16"]
          = f.input_field :num_of_guest, as: :select, id: 'header-search-guests', collection: arr, default:  [1]
  .row.row-space-top-2
    .col-sm-12
      = button_tag(type: 'submit', class: 'btn btn-primary btn-large btn-block') do
        i.fa.fa-search
        = t('.submit')

app/views/shared/_host_sidenav.html.slim
ul.sidenav-list
  li
    = link_to t('.listing'), listings_path, aria: {selected: (action_name != "host_reservation_manager")}, class: "sidenav-item"
  li
    = link_to 'お気に入り', favorites_path, aria: {selected: (controller_name == "favorites" && action_name == "index")}, class: "sidenav-item"
  li
    = link_to t('.host_reservation_manager'), dashboard_host_reservation_manager_path, aria: {selected: (action_name == "host_reservation_manager")}, class: "sidenav-item row-space-2"
  li
    = link_to new_listing_path, class: "btn btn-host" do
      span.hide--sp
        = t '.text1'
      = t '.text2'

app/views/shared/_manage_listing_header.html.slim
.manage-listing-header
  .subnav.ml-header-subnav[data-sticky="true"]
    = link_to listings_path, class: "subnav-item pull-left-absolute"
      i.fa.fa-long-arrow-left
      span 
        = t '.to_my_listings'
    .h5.text-center.text-contrast
      = listing.title
    - unless @listing.open.blank? 
      = link_to listing_path(listing.id), class: "subnav-item pull-right-absolute"
        i.fa.fa-eye
        span 
          = t '.preview'
  .subnav-placeholder.hide

app/views/shared/_manage_listing_nav.html.slim
- left_steps = @listing.left_steps
- left_step_count = @listing.left_step_count
.manage-listing-nav.col-md-3
  .row.nav-sections
    .section-header.row-space-1
      = t '.header'
    ul.list-unstyled.row-space-4
      li.nav-item class=("nav-active" if controller_name == "listings")
        = link_to new_or_edit_path(@listing) do
          = t '.basic_info'
          i.fa.fa-check
      li.nav-item class=("nav-active" if controller_name == "listing_images")
        = link_to manage_listing_listing_images_path(@listing.id) do
          = t '.image'
          - if left_steps.has_key?(:listing_image)
            i.fa.fa-exclamation-circle
          - else
            i.fa.fa-check
      - if Settings.calender_swicth == 'ok'
        li.nav-item class=("nav-active" if controller_name == "listing_okevents")
          = link_to manage_listing_listing_okevents_path(@listing) do
            = t '.cal'
            i.fa.fa-plus
      - else
        li.nav-item class=("nav-active" if controller_name == "listing_ngevents")
          = link_to manage_listing_listing_ngevents_path(@listing) do
            = t '.cal'
            i.fa.fa-plus
    .col-xs-12.text-center
      - if left_step_count.zero?
        = link_to t('.publish'), listing_publish_path(@listing), class: "btn btn-primary btn-block", id: "listing-manager-open"
      - else
        = link_to "#", class: "btn btn-primary btn-block disabled" do
          = t('.step', num: left_step_count)
      - if @listing.open.present?
        = link_to listing_unpublish_path(@listing), class: "hide-this-listing" do
          i.fa.fa-ban
          = t '.unpublish'
      - else
        .unpublished.row-space-top-2
          i.fa.fa-ban.fa-danger
          = t '.unpublished'

app/views/shared/_profile_sidenav.html.slim
ul.sidenav-list
  li
    = link_to t('.edit'), edit_profile_path, class: "sidenav-item", aria: {selected: (controller_name == 'profiles')}
  li
    = link_to t('.edit_image'), edit_profile_profile_image_path, class: "sidenav-item", aria: {selected: (controller_name == 'profile_images')}
  li
    = link_to t('.edit_identification'), profile_identification_url, class: "sidenav-item", aria: { selected: (controller_name == 'identifications')}
  li
    = link_to t('.edit_bank_account'), profile_bank_account_url, class: "sidenav-item", aria: { selected: (controller_name == 'bank_account')}

app/views/shared/_sidebar_nav_sp.html.slim
.nav-menu-wrapper
  .va-container.va-container-v.va-container-h
    .va-middle.nav-menu.card-body
      ul.menu-group.list-unstyled.row-space-3
        - if user_signed_in?
          li
            = link_to t('.home'), root_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to t('.dashboard'), dashboard_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to t('.new_listing'), new_listing_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to message_threads_path, class: "link-reset menu-item", rel: "nofollow" do
              = t '.message'
              i.alert-count.unread-count--sp.fade.text-center
              = t('.unread_msg', num: unread_messages)
          li
            = link_to t('.host_reservation_manager'), dashboard_host_reservation_manager_path, class: "link-reset menu-item", rel: "nofollow"
          /li
            /= link_to t('.wishlists'), wishlists_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to t('.profile'), edit_profile_path, class: "link-reset menu-item", rel: "nofollow" 
          li
            = link_to t('.account'), edit_user_registration_path, class: "link-reset menu-item", rel: "nofollow"
        - else
          li
            = link_to t('.home'), root_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to t('.login'), new_user_session_path, class: "link-reset menu-item", rel: "nofollow"
          li
            = link_to t('.guest_flow'), "#", class: "link-reset menu-item guest-flow-trigger", rel: "nofollow"
        li
          = link_to t('.search'), "#", class: "search-modal-trigger link-reset menu-item", rel: "nofollow"
      ul.menu-group.list-unstyled.row-space-3
        li.hide
          = link_to t('.help'), "#", class: "link-reset menu-item", rel: "nofollow"
        - if user_signed_in?
          li
            = link_to t('.logout'), destroy_user_session_path, method: :delete, class: "link-reset menu-item", rel: "nofollow"

app/views/shared/_subnav.html.slim
/ shared/subnav
.subnav.hide--sp[data-sticky="true"]
  .page-container
    ul.subnav-list.list-unstyled
      - active = action_name !="guest_reservation_manager" && action_name !="host_reservation_manager" && controller_name =="dashboard"
      li class=("active" if active)
        = link_to t('.dashboard'), dashboard_path

      - active = controller_name =="messages" || controller_name =="message_threads"
      li class=("active" if active)
          = link_to t('.messages'), message_threads_path

      - active = controller_name =="listings" || action_name =="host_reservation_manager"
      li class=("active" if active)
        = link_to t('.listings'), listings_path

      - active = action_name =="guest_reservation_manager"
      li class=("active" if active)
        = link_to t('.guest_reservation_manager'), dashboard_guest_reservation_manager_path

      /- if controller_name =="wishlists"
        /li.active
          /= link_to Settings.page.wishlists, wishlists_path
      /- else
        /li
          /= link_to Settings.page.wishlists, wishlists_path

      - active = controller_name =="profiles" || action_name == "review" || controller_name == 'profile_images'
      li class=("active" if active)
        = link_to t('.profile'), edit_profile_path

      - active = params[:mode] =="account"
      li class=("active" if active)
          = link_to t('.account'), edit_user_registration_path(mode: "account")

.subnav-placeholder.hide--sp.hide

app/views/shared/_tooltip.html.slim
.popover-wrapper.privacy-tooltip
  .popover-container
    .card-body
      h5
        = t '.all_user.title'
      p
        = t '.all_user.text'
    .card-body
      h5
        = t '.only_me.title'
      p
        = t '.only_me.text'
.popover-wrapper.zipcode-tooltip
  .popover-container
    .card-body
      p
        = t '.zipcode'
.popover-wrapper.togo-tooltip
  .popover-container
    .card-body
      h5
        = t '.delivery.title'
      p
        = t '.delivery.text'
        br
    .card-body
      h5
        = t '.reliability.title'
      p
        = t('.reliability.text_html')

app/views/shared/_triplets.html.slim
.page-container.col-center.hide--sp
  .row.row-space-2.row-space-top-8
    .col-4.text-center
      i.fa.fa-hand-o-up.fa-c-heart.fa-size-3
      h4
        = t '.first.title'
      .text-lead.text-color-light
        = t '.first.text'
    .col-4.text-center
      i.fa.fa-heart.fa-c-heart.fa-size-3
      h4
        = t '.second.title'
      .text-lead.text-color-light
        = t '.second.text'
        a[href="/terms/host_guarantee"]
          = t '.second.link'
        = t '.second.link_text'
    .col-4.text-center
      i.fa.fa-lock.fa-c-heart.fa-size-3
      h4
        = t '.third.title'
      .text-lead.text-color-light
        = t '.third.text'